# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qD6-bMHmNEt7dAAtVrBFLfHKkQdC7ZDS
"""

import numpy as np
array=[10,20,30]
array1=[40,50,60]
result(array,array+array1)
print(result)